spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mariadb://localhost:3306/highscores
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  application:
    name: highscores

server:
  port: 8080